# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a940645206e7f26d7a6bb777ddee167b60b0c7227cc41ffcb8fbf63ab41c3061ba476dcc9612172f6698b6bdb9ab53933b2d0cd4edfedd9ddb9ce0700196d9c

test:
  secret_key_base: 34d4ccdd4876769dc4d8766c8ddb5c6de70bdd3c7ea702f3b5af470af2bab3acff07480bf38e109c09155825714d6c603163c0772400e48e417b1717d9d96327

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
